language: ruby
sudo: false
dist: precise
cache: bundler
rvm:
- 2.3.3
before_script: cp config/database.example.yml config/database.yml && bundle exec rake
  db:schema:load
branches:
  except:
  - CURRENT
env:
  global:
  - secure: Q+fmUEp3COuM/n1lER3oU3NWrZasO3QcQZ6AYDrAFkBjVerjCfCPIyG1aEbeVF7+FpqcTKecNxe2vGpz0g6erhkxdx5sHXFFu+rKXShsdtR7yYwTsn9VRRbguBLTynNOoYFIVugXKSAJoXtuTzrZxtSgHo3GRexlhMQWNtauT24=
  - secure: Oin78sjiTfcKmO4KTQbNy/5Pivj+0sVG7W3Royq2NnLGyIkHuX30AlQRpc/fmQGT3aXRGgzBe9MznhETAPtUisDt4EbkRNUlnWLTLUIOlrhNkoNo3rEwWR1hIrvVDDBhysMli367e9dqQ0P/ymo6B+WVcT6fey7g+JmUBExITyU=
  - secure: fke53ZVI415GXIhIQ8POwWC7YOnRaKmvzW462+kg7nUsrn066MakkXFJkteTYRCYnYBKRA5dCO4vuwci9TifaQB2KmSvIhot2LZJ+Z1O7GTdPxKwLdwk34KuqYnVbmaS6O/noI5+0DHIPM9SMvazJIgmemAQpzejBTLNpnT/4B8=
  - secure: a43FgkoIGSbARBwni6O+48rYxHdT12yp35Quo1IBSv2MywqEJQ8K1+0OGWwNfHwtwjIpK/MG0NEntajsWYRer/9YncOP0O3SuZwO8IPUnWgbVP5XSHxoGHZuWMAhlmuwx66dt+Yrdb7ZzP1PTD/zb8a01X50soYtbKpJlTrux0o=
  - secure: K8ck0lX/cC6pl++6lp+pBzLUHE1NL+ldF7/5x/6/+TiLUCPp3X+EQaa1TSe8UnY1Dot+XxdQ5Z1BKBcmn1ebqnBz8zoxCKdaKZpXiifuKud9p9Xf4HAloy78Nb/8HfMPBfVkxfUFfxDJWhTskVmbhKv5Q7+9I8QBt4XOL/Axxww=
  - secure: MiZJ+pmU5stria23Cbf5AZEmMtSJmTyQAoFHY18n0MbcJbUHCquiG7E2HhzM6h9vvBnSBF1dKEV6p5XlZNs06MRvId/R4qkb8OL35QVqbQyrot7RHBlKaBaAeKrHheYNi4Sm5FiAOmCt6xgu9sMcdcVfDwJLEnjJyZHZzUuxWyI=
  - FOUNDING_PARTNER_ID=NU4997LN
  - XPC_SERVICE_NAME=0
  - TEST_COVERAGE=1
  - RACKSPACE_API_REGION=lon
  - secure: AU7M7tWv2LOj/CHO/cr0l92+GxK1IQ/1u8cPIIl4huP7VbPw+8KUg0BiB6RT0FZ2+Himd1DyfGFwlTGUXlskCHnW3uNXBOYz++kmGkRwvNJaxxgQ114KyD2NkAfNSH2h9hWgMtE73rUcbXQJXw9pPuxKUOqe1opi0tSL4/e24f8=
