language: ruby
sudo: required
dist: precise
cache: bundler
before_install:
- gem install bundler
rvm:
- 1.9.3
before_script: cp config/database.example.yml config/database.yml && bundle exec rake
  db:schema:load
services: redis
after_success:
- ! '[ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ] &&
  curl -v -X DELETE -u $GITHUB_USER:$GITHUB_PASSWORD "https://api.github.com/repos/$TRAVIS_REPO_SLUG/git/refs/tags/CURRENT"'
- ! '[ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ] &&
  curl -v -X POST -d ''{"ref":"refs/tags/CURRENT","sha":"''$TRAVIS_COMMIT''"}''  --header
  "Content-Type:application/json" -u $GITHUB_USER:$GITHUB_PASSWORD "https://api.github.com/repos/$TRAVIS_REPO_SLUG/git/refs"'
- ! '[ "$TRAVIS_BRANCH" == "staging" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ] &&
  curl -v -X DELETE -u $GITHUB_USER:$GITHUB_PASSWORD "https://api.github.com/repos/$TRAVIS_REPO_SLUG/git/refs/tags/STAGING"'
- ! '[ "$TRAVIS_BRANCH" == "staging" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ] &&
  curl -v -X POST -d ''{"ref":"refs/tags/STAGING","sha":"''$TRAVIS_COMMIT''"}''  --header
  "Content-Type:application/json" -u $GITHUB_USER:$GITHUB_PASSWORD "https://api.github.com/repos/$TRAVIS_REPO_SLUG/git/refs"'
branches:
  except:
  - CURRENT
notifications:
  irc:
    channels:
    - irc.freenode.net#theodi
    template:
    - ! '%{repository} %{branch} - %{message} %{build_url}'
    on_success: change
    on_failure: always
env:
  global:
  - secure: gVjzB18+9Tk+Zb3s+t63wL1I6KhrIZlY+w7YBBF6l7/1At4bOoWsscWrswohsbbQ5jW85mScDqAiX0vNQPqQXw92AAJ9c8aOFm1IyItz5cwV/Tep+p632iuAopqCi7QQ1p38BMpH37VU2WCKo8o/PjBiPbdi6cI8jO5Dwa8zf9c=
  - secure: Y+uNul1jHcpmE/pTwwuqWVAyDEv70xWty9X5tdQq507VOOajiWKtSwkpBbDyynviZJFIylT9xTU+A2AhRbHCosLfR9egAwE2eXiL4XVnwrLyMunl6D+l2mHzFYkEJqaA5vIdl3fwILr8bJUOHQSeHyXUZK9dduINftVlbQnmlTc=
  - secure: WM2RWJh5xAe5n0azU+bjMGLn2e7JzCAZJQy1uTabG9zzsDCr0k4PO/kuhfPNh1hbKamZhcPsGnR2NnNQeNdqesIfF4tiCkPwwOc7RBZFi48G6gmNltmtk2MVBV9DFZmpXDCgJ4s1xqdlAuvquRM5HFtEVaKaiEbB171T8swEaRU=
  - secure: I1CsTofRuE9oH3yauJSMdpuDSPl19JIPVcqnC3jbk0iVDwMHthXS8C1SrfhhcdiJ8uN0ILd0BLLJ2w4OU20Pe2WPNCGRSTntYx/qy4Dq0n1oHnr/DPyT1LG3UleRlhzYZ7CLSXvn6Zq+9sf3kOWn+ClFy6uGU2keWZ6ZuyC6Ya8=
  - secure: CW10yIxbmM3SFMZ/Sbsw7yv4fBZy8qWUgDKIT8jjB2sIhV3bip3h1IiUSbCzTXW+bKgDpCN1WUrsNFlXIavUZrNRuWpu4P+hofclUmFfbfKCl0FYrbQSjEtd8apgVOr+IgAsvrbXbeq9ht02DFs4spu8GFtF1mBXOV2+rJnWCNk=
  - secure: QMhC+QWarZcagWC6OspZt9CS4YWZ8dIFoNGP9xtgOjZzT0yuuZ1tH7B7QHAjH9ER68tTD5bipJkM/6hxI/5yl2HD6mPK4Y83+Xodmir6PXUIguN+/4u9FXaYTxFuQ8FBusxhKH0P44Utru41WLlJxpkN0uIgwvgsQ4pLz9GbWUc=
  - secure: ExLak+mMD6TAn6EuAI2x6D+1NOVgqmoBg2XkiOq6xc1R0f7PPvMHlve61VIVqHB4c3/Q66+7qPv87wrsx+vDSfkI7kgVogWeR4Tbk/OBx5SZSlJP+1pjHSlgkgqc1Ek0ZBaZlnRpkxYfMdIusKWHm4sYwzOAxAkftQdbQgGvvSA=
  - secure: Q+fmUEp3COuM/n1lER3oU3NWrZasO3QcQZ6AYDrAFkBjVerjCfCPIyG1aEbeVF7+FpqcTKecNxe2vGpz0g6erhkxdx5sHXFFu+rKXShsdtR7yYwTsn9VRRbguBLTynNOoYFIVugXKSAJoXtuTzrZxtSgHo3GRexlhMQWNtauT24=
  - secure: Oin78sjiTfcKmO4KTQbNy/5Pivj+0sVG7W3Royq2NnLGyIkHuX30AlQRpc/fmQGT3aXRGgzBe9MznhETAPtUisDt4EbkRNUlnWLTLUIOlrhNkoNo3rEwWR1hIrvVDDBhysMli367e9dqQ0P/ymo6B+WVcT6fey7g+JmUBExITyU=
  - secure: fke53ZVI415GXIhIQ8POwWC7YOnRaKmvzW462+kg7nUsrn066MakkXFJkteTYRCYnYBKRA5dCO4vuwci9TifaQB2KmSvIhot2LZJ+Z1O7GTdPxKwLdwk34KuqYnVbmaS6O/noI5+0DHIPM9SMvazJIgmemAQpzejBTLNpnT/4B8=
  - secure: a43FgkoIGSbARBwni6O+48rYxHdT12yp35Quo1IBSv2MywqEJQ8K1+0OGWwNfHwtwjIpK/MG0NEntajsWYRer/9YncOP0O3SuZwO8IPUnWgbVP5XSHxoGHZuWMAhlmuwx66dt+Yrdb7ZzP1PTD/zb8a01X50soYtbKpJlTrux0o=
  - secure: K8ck0lX/cC6pl++6lp+pBzLUHE1NL+ldF7/5x/6/+TiLUCPp3X+EQaa1TSe8UnY1Dot+XxdQ5Z1BKBcmn1ebqnBz8zoxCKdaKZpXiifuKud9p9Xf4HAloy78Nb/8HfMPBfVkxfUFfxDJWhTskVmbhKv5Q7+9I8QBt4XOL/Axxww=
  - secure: MiZJ+pmU5stria23Cbf5AZEmMtSJmTyQAoFHY18n0MbcJbUHCquiG7E2HhzM6h9vvBnSBF1dKEV6p5XlZNs06MRvId/R4qkb8OL35QVqbQyrot7RHBlKaBaAeKrHheYNi4Sm5FiAOmCt6xgu9sMcdcVfDwJLEnjJyZHZzUuxWyI=
  - STRIPE_API_KEY=fakeapikey
  - FOUNDING_PARTNER_ID=NU4997LN
  - XPC_SERVICE_NAME=0
  - TEST_COVERAGE=1
  - RACKSPACE_API_REGION=lon
  - CHARGIFY_COMPONENT_ID=1234
  - secure: AU7M7tWv2LOj/CHO/cr0l92+GxK1IQ/1u8cPIIl4huP7VbPw+8KUg0BiB6RT0FZ2+Himd1DyfGFwlTGUXlskCHnW3uNXBOYz++kmGkRwvNJaxxgQ114KyD2NkAfNSH2h9hWgMtE73rUcbXQJXw9pPuxKUOqe1opi0tSL4/e24f8=
  - CHARGIFY_PRODUCT_URL=https://theodi-testing.chargify.com/subscribe/%s/%s
  - CHARGIFY_PAGE_IDS='individual_supporter,mjfzzwgm|individual_supporter_student_free,bdbytczwymyc|individual_supporter_student,rvx5rnhsx9pt|corporate_supporter_annual,j2rjxnps|supporter_monthly,gmb6y2cm|supporter_annual,35jqgq8q'
  - CHARGIFY_SUBDOMAIN=theodi-testing
  - secure: io/xuObALiz1tPInEo0pKc+Dn5mvwiJHS/5bn1TYOeMsjekvHkcQG3hTGiJtylzaNinXWz3dxxS0yoEJcRXE3NLdCdLZgL6waH93x9HxF2A1YDix0Oyahli1gFPtPPhVRoA6VnQ3gux7JR5vGJZ18y4M4H9ZYEQQAj05yYJglyo=
  - secure: dc5SIVEFQIb7vCG86CYR3xNTAlesZCW8GS7F/eY7UMGhFwpq+jurmKYxDVzttg+u1AmiyAU1QmAwXl++rOPFHh8JfTZqjagv5LznEc1SUqCfpBjheOtVA66drp0D4yY7Djv1VAUYFKwyN6t5Ur1gYek+gMJj3RK2PPC1DDX+7Bk=
