version: '2'
services:
  web:
    image: directory
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ".:/usr/src/app"
    depends_on:
      - redis
      - mysql
  redis:
    image: redis
  mysql:
    image: mysql:5.5.48
    environment:
      MYSQL_ROOT_PASSWORD: secretsquirrel
      MYSQL_USER: theodi
      MYSQL_PASSWORD: secretsquirrel
      MYSQL_DATABASE: development
    volumes:
      - mysqldata:/var/lib/mysql
volumes:
  mysqldata:
    driver: local
