# encoding: utf-8
class University
  def self.names
    [
      "Aberdeen",
      "Abertay",
      "Aberystwyth",
      "Anglia Ruskin",
      "Arts University Bournemouth",
      "Aston",
      "Bangor",
      "Bath",
      "Bath Spa",
      "Bedfordshire",
      "Birkbeck",
      "Birmingham",
      "Birmingham City",
      "Bishop Grosseteste",
      "Bolton",
      "Bournemouth",
      "BPP University",
      "Bradford",
      "Brighton",
      "Bristol",
      "Brunel",
      "Buckingham",
      "Bucks New",
      "Cambridge",
      "Canterbury Christ Church",
      "Cardiff",
      "Cardiff Metropolitan",
      "Central Lancashire",
      "Chester",
      "Chichester",
      "City",
      "Courtauld Institute of Art",
      "Coventry",
      "Cumbria",
      "De Montfort",
      "Derby",
      "Dundee",
      "Durham",
      "Durham University Business School",
      "East Anglia",
      "East London",
      "Edge Hill",
      "Edinburgh",
      "Edinburgh Napier",
      "Essex",
      "Exeter",
      "Faculty of Health, Social Care and Education",
      "Falmouth",
      "Glasgow",
      "Glasgow Caledonian",
      "Gloucestershire",
      "Glyndŵr",
      "Goldsmiths",
      "Greenwich",
      "Harper Adams",
      "Heriot-Watt",
      "Hertfordshire",
      "Heythrop College",
      "Highlands and Islands",
      "Huddersfield",
      "Hull",
      "Imperial College London",
      "Keele",
      "Kent",
      "King's College London",
      "Kingston",
      "Lancaster",
      "Leeds",
      "Leeds Beckett",
      "Leeds Trinity University",
      "Leicester",
      "Lincoln",
      "Liverpool",
      "Liverpool Hope",
      "Liverpool John Moores",
      "London Metropolitan",
      "London School of Economics",
      "London South Bank",
      "Loughborough",
      "Manchester",
      "Manchester Metropolitan",
      "Manchester School of Architecture",
      "Medway School of Pharmacy",
      "Middlesex",
      "Newcastle",
      "Newman",
      "Northampton",
      "Northumbria",
      "Norwich University of the Arts",
      "Nottingham",
      "Nottingham Trent",
      "Open University",
      "Oxford",
      "Oxford Brookes",
      "Oxford Brookes University Business School",
      "Pearson College",
      "Plymouth",
      "Portsmouth",
      "Queen Margaret",
      "Queen Mary",
      "Queen's – Belfast",
      "Reading",
      "Robert Gordon",
      "Roehampton",
      "Royal Academy of Music",
      "Royal Agricultural University",
      "Royal Central School of Speech and Drama",
      "Royal College of Music",
      "Royal Conservatoire of Scotland",
      "Royal Holloway",
      "Royal Northern College of Music",
      "Royal Veterinary College",
      "Salford",
      "Sheffield",
      "Sheffield Hallam",
      "SOAS",
      "South Wales",
      "Southampton",
      "Southampton Solent",
      "St Andrews",
      "St George's, University of London",
      "St Mark and St John",
      "St Mary's",
      "Staffordshire",
      "Stirling",
      "Strathclyde",
      "Sunderland",
      "Surrey",
      "Sussex",
      "Swansea",
      "Teesside",
      "Trinity Saint David",
      "UCFB",
      "Ulster",
      "University Campus Suffolk",
      "University College Birmingham",
      "University College London",
      "University College London",
      "University for the Creative Arts",
      "University of Law",
      "University of the Arts London",
      "Warwick",
      "West London",
      "West of England, Bristol",
      "West of Scotland",
      "Westminster",
      "Winchester",
      "Wolverhampton",
      "Worcester",
      "York",
      "York St John"
    ]
  end
  
  def self.select_name(str)
    if University.names.include?(str)
      str
    else
      "Other (please specify)"
    end
  end
    
  def self.select_name_other(str)
    if University.names.include?(str)
      nil
    else 
      str
    end
  end
    
end

